### ISSUE TITLE
Release beta & Add binaries distribution

### ISSUE THREAD

**Issue by keizo042** [opentoonz/dwango_opentoonz_plugins#2]
ユーザ向けにバイナリの配布を行う必要があると感じます。

twitterなどで非開発者ユーザがプラグインを試す際、githubに参照を飛ばされるため
困惑している様子が見受けられました。
おいおいgithub pagesなどで分かりやすく配布するとよいと思いますが、
急場の対策として、github releaseでビルド済み
バイナリを配布するのはいかがでしょうか。
ざっくりやるとこんな感じで name_version_os.zip の形式でWindows/Macそれぞれに配布するのが
良いと思われます。

[dwango_opentoonz_plugins_MacOSX_El_Capitan.zip](https://github.com/opentoonz/dwango_opentoonz_plugins/files/191595/dwango_opentoonz_plugins_MacOSX_El_Capitan.zip)

**Comment by kogaki** [comment]
Thank you for your advice. I've updated README for pre-built binaries.

コメントありがとうございます。バイナリは既に同梱していたんですが、READMEに利用方法が抜けていました。READMEを更新しましたので、よろしければご確認お願いします。

**Comment by keizo042** [comment]
Good Job, Thank you : )
